blueprints/auth.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session
from exts import db, mail
from flask_mail import Message
import string
import random
from models import EmailCaptchaModel, UserModel
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash

# /auth
bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                print("邮箱在数据库中不存在！")
                return redirect(url_for("auth.login"))
            if check_password_hash(user.password, password):
                # cookie:
                # cookie中不适合存储太多的数据，只适合存储少量的数据
                # cookie一般用来存放登录授权的东西
                # flask中的session，是经过加密后存储在cookie中的
                session['user_id'] = user.id
                return redirect("/")
            else:
                print("密码错误！")
                return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.login"))


# GET：从服务器获取数据，获取页面的数据
# POST：把客户端的数据提交给服务器，当点提交时就是post
@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        # 验证用户提交的邮箱和验证码是否对应且正确
        # 表单验证：flask-wtf：wtforms
        form = RegisterForm(request.form)# 调用form中registerform中的验证函数
        if form.validate():#如果验证成功
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login"))
        else:
            # print(form.captcha)
            # print(form.password_confirm)
            print(form.errors)
            return redirect(url_for("auth.register"))


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")

# bp.route:如果没有指定methods参数，默认就是GET请求
@bp.route("/captcha/email")
def get_email_captcha():
    # /captcha/email/<email>
    # /captcha/email?email=xxx@qq.com
    email = request.args.get("email")
    # 4/6: 随机数字、字母、数字和字母的组合
    source = string.digits * 4 #0123456789012345678901234567890123456789
    captcha = random.sample(source, 4)
    captcha = "".join(captcha) # 从列表到字符串
    message = Message(subject="知了传课注册验证码", recipients=[email], body=f"您的验证码是：{captcha}")
    mail.send(message)
    # memcached/redis
    # 用数据库表的方式存储
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    # Restful Api
    # {code: 200/400/500, message: "", data: {}}
    return jsonify({"code": 200, "message": "", "data": None})


@bp.route("/mail/test")
def mail_test():
    message = Message(subject="邮件测试", recipients=["1078645982@qq.com"], body="这是一条测试邮件")
    mail.send(message)
    return "邮件发送成功！"

blueprints/qa.py
from flask import Blueprint, render_template, request, redirect, url_for, g
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from decorators import login_required


bp = Blueprint("qa", __name__, url_prefix="/")


# http://127.0.0.1:5000
@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template("index.html", questions=questions)


@bp.route("/qa/public", methods=['GET', 'POST'])
@login_required#会把下面的public_question传给login_required装饰器
def public_question():
    if request.method == 'GET':
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            # todo: 跳转到这篇问答的详情页
            return redirect("/")
        else:
            print(form.errors)
            return redirect(url_for("qa.public_question"))


@bp.route("/qa/detail/<qa_id>")
def qa_detail(qa_id):
    question = QuestionModel.query.get(qa_id)
    return render_template("detail.html", question=question)


@bp.route("/answer/public", methods=['POST'])
@bp.post("/answer/public")
@login_required
def public_answer():
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        answer = AnswerModel(content=content, question_id=question_id, author_id=g.user.id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("qa.qa_detail", qa_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for("qa.qa_detail", qa_id=request.form.get("question_id")))


@bp.route("/search")
def search():
    # /search?q=flask
    # /search/<q>
    # post, request.form
    q = request.args.get("q")
    questions = QuestionModel.query.filter(QuestionModel.title.contains(q)).all()
    return render_template("index.html", questions=questions)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}-知了课堂问答平台</title>
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>  
            </button>
            <a class="navbar-brand" href="#">
                <img class="logo" src="{{ url_for('static',filename='images/zhiliaologo.png') }}" alt="">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="/">首页<span class="sr-only">(current)</span></a>
                </li>
                <li>
                    <a href="{{ url_for('qa.public_question') }}">发布问答</a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" action="{{ url_for('qa.search') }}" method="get">
                <div class="form-group">
                    <input name="q" type="text" class="form-control" placeholder="请输入关键字">
                </div>
                <button type="submit" class="btn btn-default">查找</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user %}
                    <li><a href="#">{{ user.username }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    <li><a href="{{ url_for('auth.register') }}">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="main">
    {% block main %}{% endblock %}
</div>
</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block title %}{{ question.title }}-{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title">{{ question.title }}</h3>
    <p class="question-info">
        <span>作者：{{ question.author.username }}</span>
        <span>时间：{{ question.create_time }}</span>
    </p>
    <hr>
    <p class="question-content">{{ question.content }}</p>
    <hr>
    <h4>评论：（{{ question.answers|length }}）</h4>
    <form action="{{ url_for('qa.public_answer') }}" method="post">
        <div class="form-group">
            <input name="content" type="text" class="form-control" placeholder="请填写评论">
            <input type="hidden" name="question_id" value="{{ question.id }}">
        </div>
        <div class="form-group" style="text-align: right;">
            <button class="btn btn-primary">立即评论</button>
        </div>
    </form>
    <ul class="answer-list">
        {% for answer in question.answers %}
            <li>
                <div class="user-info">
                    <img src="{{ url_for('static',filename='images/zhiliao.png') }}" alt="" class="avatar">
                    <span class="username">{{ answer.author.username }}</span>
                    <span class="create-time">{{ answer.create_time }}</span>
                </div>
                <p class="answer-content">{{ answer.content }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block main %}
    <ul class="question-list-group">
        {% for question in questions %}
            <li>
                <div class="avatar-group">
                    <img src="{{ url_for('static',filename='images/zhiliao.png') }}" alt="" class="avatar">
                </div>
                <div class="question-group">
                    <p class="question-title"><a
                            href="{{ url_for('qa.qa_detail', qa_id=question.id) }}">{{ question.title }}</a></p>
                    <p class="question-content">{{ question.content }}</p>
                    <div class="question-info">
                        <span class="question-author">{{ question.author.username }}</span>
                        <span class="question-time">{{ question.create_time }}</span>
                    </div>
                </div>
            </li>
        {% endfor %}

    </ul>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}登录{% endblock %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login_register.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title">登录</h3>
    <form method="POST">
        <div class="form-container">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="邮箱" name="email">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="密码" name="password">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block">登录</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/public_question.html
{% extends 'base.html' %}

{% block title %}发布问答{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/question.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title">发布问答</h3>
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <input type="text" placeholder="请输入标题" name="title" class="form-control">
            </div>
            <div class="form-group">
                <textarea name="content" rows="5" placeholder="请输入内容" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary">立即发布</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}注册{% endblock %}

{% block head %}
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/register.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login_register.css') }}">
{% endblock %}

{% block main %}
    <h3 class="page-title">注册</h3>
    <form method="POST">
        <div class="form-container">
            <div class="form-group">
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="邮箱" name="email">
            </div>

            <div class="form-group" style="display: flex">
                <input type="text" class="form-control" placeholder="验证码" name="captcha"
                       style="width: 214px;">
                <button id="captcha-btn">获取验证码</button>
            </div>

            <div class="form-group">
                <input type="text" class="form-control" placeholder="用户名" name="username">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="密码" name="password">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="确认密码" name="password_confirm">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block">立即注册</button>
            </div>
        </div>
    </form>
{% endblock %}